### ISSUE TITLE
test suite failure with lxd-client-config-0.1.0.0

### ISSUE THREAD

**Issue by DanBurton** [hverr/haskell-lxd-client-config#1]
As seen on the stackage build server:

```
encode/decode: [OK, passed 100 tests]
decode file: [Failed]
ERROR: InvalidYaml (Just (YamlException "Yaml file not found: data/example-config.yml"))

         Properties  Test Cases  Total      
 Passed  1           0           1          
 Failed  0           1           1          
 Total   1           1           2  
```

This is likely due to the fact that stackage runs tests from your hackage tarball, which means you just need to declare this test file as part of the package via the "extra-files" field in your cabal file.

**Comment by hverr** [comment]
Thanks for spotting this! Fixed in #2. Will submit a PR to fpco/stackage to re-enable tests.
